- name: Creating empty file and symbolic link stapp01
  hosts: stapp01
  become: yes
  tasks:      
    - name: Create file and link 
      file:
        path: /opt/finance/blog.txt
        owner: tony
        group: tony
        state: touch    
    - name: Create  link 
      file:
        src: /opt/finance
        dest: /var/www/html        
        state: link

- name: Creating empty file and symbolic link stapp02
  hosts: stapp02
  become: yes
  tasks:      
    - name: Create file and link 
      file:
        path: /opt/finance/story.txt
        owner: steve
        group: steve
        state: touch    
    - name: Create  link 
      file:
        src: /opt/finance
        dest: /var/www/html        
        state: link

- name: Creating empty file and symbolic link stapp03
  hosts: stapp03
  become: yes
  tasks:      
    - name: Create file and link 
      file:
        path: /opt/finance/media.txt
        owner: banner
        group: banner
        state: touch    
    - name: Create  link 
      file:
        src: /opt/finance
        dest: /var/www/html        
        state: link



# Different way to do above task

hosts: stapp01, stapp02, stapp03

become: yes

tasks:

  - name: Create the blog.txt on stapp01

    file:

      path: /opt/itadmin/blog.txt

      owner: tony

      group: tony

      state: touch

    when: inventory_hostname == "stapp01"

  - name: Create the story.txt on stapp02

    file:

      path: /opt/itadmin/story.txt

      owner: steve

      group: steve

      state: touch

    when: inventory_hostname == "stapp02"

  - name: Create the media.txt on stapp03

    file:

      path: /opt/itadmin/media.txt

      owner: banner

      group: banner

      state: touch

    when: inventory_hostname == "stapp03"

  - name: Link /opt/itadmin directory

    file:

      src: /opt/itadmin/

      dest: /var/www/html

      state: link

