apiVersion: v1
kind: Pod
metadata:
  name: volume-share-nautilus
  labels: 
    app: volume-share
spec:
  containers:
    - name: volume-container-nautilus-1
      image: debian:latest
      command: ["/bin/sh", "sleep 4600"]
      volumeMounts:
      - mountPath: "/tmp/official"
        name: volume-share
    - name: volume-container-nautilus-2
      image: debian:latest
      command: ["/bin/sh", "sleep 4600"]
      volumeMounts:
      - mountPath: "/tmp/cluster"
        name: volume-share
  volumes:
    - name: volume-share
      emptyDir: {}