apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;

    # Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
    include /usr/share/nginx/modules/*.conf;

    events {
        worker_connections 1024;
    }

    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile            on;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   65;
        types_hash_max_size 4096;

        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;

        # Load modular configuration files from the /etc/nginx/conf.d directory.
        # See http://nginx.org/en/docs/ngx_core_module.html#include
        # for more information.
        include /etc/nginx/conf.d/*.conf;

        server {
            listen       8095;
            listen       [::]:8095;
            server_name  _;
            root         /var/www/html;
            index index.html index.htm index.php;

            # Load configuration files for the default server block.
            include /etc/nginx/default.d/*.conf;

            error_page 404 /404.html;
            location = /404.html {
            }

            error_page 500 502 503 504 /50x.html;
            location = /50x.html {
            }
        }


    }
        
    
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-phpfpm
  labels:
        app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
      - containerPort: 8095 
    volumeMounts:
    - name: nginx-config-volume
      mountPath: /etc/nginx/nginx.conf 
      subPath: nginx.conf
      readOnly: true
    - name: shared-files
      mountPath: /var/www/html   
  - name: php-fpm-container
    image: php:7.0-fpm
    volumeMounts:
    - name: shared-files
      mountPath: /var/www/html    
  volumes:
  - name: nginx-config-volume 
    configMap:
      name: nginx-config 
      items:
        - key: nginx.conf
          path: nginx.conf  
          volumes:
  - name: shared-files
    emptyDir: {}  
 

---   
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
  - port: 30012
    targetPort: 8095
  selector:
    app: nginx