apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-xfusion  
spec:
  capacity:
   storage: 4Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/mnt/itadmin"
  storageClassName: manual
  

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-xfusion
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 3Gi
  storageClassName: manual

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-xfusion
  labels: 
    app: pv-xfusion
spec:
  containers:
    - name: container-xfusion
      image: httpd:latest
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: pvc-xfusion

---
apiVersion: v1
kind: Service
metadata:
  name: web-xfusion  
spec:
  type: NodePort
  selector:
    app: pod-xfusion
  ports:      
    - port: 80
      targetPort: 80     
      nodePort: 30008