apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis-master
    tier: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-master
      tier: back-end
  template:
    metadata:
      labels:
        app: redis-master
        tier: back-end
    spec:
      containers:
      - name: master-redis-datacenter
        image: redis
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"         
        ports:
        - containerPort: 6379
---
apiVersion: v1                    
kind: Service                      
metadata:
  name: redis-master         
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379    
  selector:                       
    app: redis-master
    tier: back-end
   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  labels:
    app: redis-slave
    tier: back-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-slave
      tier: back-end
  template:
    metadata:
      labels:
        app: redis-slave
        tier: back-end
    spec:
      containers:
      - name: slave-redis-datacenter
        image: gcr.io/google_samples/gb-redisslave:v3
        env:
        - name: GET_HOSTS_FROM
          value: "dns"
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"          
        ports:
        - containerPort: 6379

---
apiVersion: v1                    
kind: Service                      
metadata:
  name: redis-slave      
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379    
  selector:                       
    app: redis-slave
    tier: back-end

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
      tier: front-end
  template:
    metadata:
      labels:
        app: guestbook
        tier: front-end
    spec:
      containers:
        - name: php-redis-datacenter
          image: gcr.io/google-samples/gb-frontend:v4
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 80

---
apiVersion: v1                    
kind: Service                      
metadata:
  name: frontend   
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
  selector:                       
    app: guestbook
    tier: front-end
    