apiVersion: v1
kind: ConfigMap
metadata:
  name: time-config
  namespace: xfusion
data:
  TIME_FREQ: "2"
    


---
apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: xfusion
  labels:
    app: time-check
spec:
  containers:
  - name: time-check
    image: busybox:latest
    volumeMounts:
    - name: log-volume
      mountPath: /opt/sysops/time
    envFrom:
    - configMapRef:
        name: time-config
    command: ["/bin/sh", "-c"]
    args: ["while true; do date; sleep $TIME_FREQ;done > /opt/security/time/time-check.log"]
  volumes:
  - name: log-volume
    emptyDir: {}